# Generated by Django 4.2.30 on 2026-07-23 15:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("drivers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PLANNED", "Planned"),
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("start_time", models.DateTimeField(db_index=True)),
                (
                    "total_distance_miles",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
                ),
                (
                    "total_duration_hours",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                ("initial_cycle_used_seconds", models.IntegerField(default=0)),
                ("compliance_report", models.JSONField(blank=True, default=dict)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="trips",
                        to="drivers.driver",
                    ),
                ),
            ],
            options={
                "db_table": "trips",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScheduleEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=None, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("sequence", models.IntegerField()),
                ("event_type", models.CharField(max_length=30)),
                (
                    "duty_status",
                    models.CharField(
                        choices=[
                            ("OFF", "Off Duty"),
                            ("SB", "Sleeper Berth"),
                            ("D", "Driving"),
                            ("ON", "On Duty Not Driving"),
                        ],
                        max_length=10,
                    ),
                ),
                ("start_time", models.DateTimeField(db_index=True)),
                ("end_time", models.DateTimeField(db_index=True)),
                ("start_latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("start_longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("end_latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("end_longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "distance_miles",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "db_table": "schedule_events",
                "ordering": ["sequence"],
            },
        ),
        migrations.CreateModel(
            name="DailyLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=None, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("log_date", models.DateField(db_index=True)),
                ("off_duty_seconds", models.IntegerField(default=0)),
                ("sleeper_berth_seconds", models.IntegerField(default=0)),
                ("driving_seconds", models.IntegerField(default=0)),
                ("on_duty_seconds", models.IntegerField(default=0)),
                ("grid_intervals", models.JSONField(default=list)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_logs",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "db_table": "daily_logs",
                "ordering": ["log_date"],
            },
        ),
        migrations.CreateModel(
            name="Waypoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=None, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("sequence", models.IntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("START", "Start Location"),
                            ("PICKUP", "Pickup Location"),
                            ("FUEL", "Fuel Stop"),
                            ("REST", "Rest Stop"),
                            ("DROPOFF", "Dropoff Location"),
                        ],
                        max_length=20,
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("duration_seconds", models.IntegerField(default=0)),
                ("address", models.CharField(blank=True, max_length=255)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waypoints",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "db_table": "waypoints",
                "ordering": ["sequence"],
                "unique_together": {("trip", "sequence")},
            },
        ),
        migrations.AddIndex(
            model_name="trip",
            index=models.Index(fields=["driver", "status"], name="trips_driver__f38efc_idx"),
        ),
        migrations.AddIndex(
            model_name="scheduleevent",
            index=models.Index(
                fields=["trip", "start_time", "end_time"], name="schedule_ev_trip_id_0bd005_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailylog",
            unique_together={("trip", "log_date")},
        ),
    ]
